routes/web.php
<?php
Route::get('/', function () {
  if(env('PLATAFORMA_RESERVACIONES') == true) {
    return redirect(('/pageWeb'));
  }
  else {
    return redirect('/admin/home');
  }
});
Route::get('/pageWeb', 'Plataforma\FrontendController@index');
Route::any('/reservar/renderBus', 'Plataforma\ReservacionController@renderBus');
Route::resource('/reservar', 'Plataforma\ReservacionController');
/*Route::get('/pagoconpaypal', function(){

    return view('frontend.paypal');
});*/

Route::get('/pagoconpaypal/{clave}', 'Plataforma\PaymentController@create')->name('pagoconpaypal');
Route::post('/paypal', 'Plataforma\PaymentController@payWithpaypal');
Route::get('/status', 'Plataforma\PaymentController@getPaymentStatus')->name('status');


// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('login', 'Auth\LoginController@login')->name('auth.login');
$this->post('logout', 'Auth\LoginController@logout')->name('auth.logout');

// Change Password Routes...
$this->get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
$this->patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');

Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index');

    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'Admin\UsersController');
    Route::post('users_mass_destroy', ['uses' => 'Admin\UsersController@massDestroy', 'as' => 'users.mass_destroy']);
    Route::resource('user_actions', 'Admin\UserActionsController');
    Route::resource('contact_companies', 'Admin\ContactCompaniesController');
    Route::post('contact_companies_mass_destroy', ['uses' => 'Admin\ContactCompaniesController@massDestroy', 'as' => 'contact_companies.mass_destroy']);
    Route::resource('contacts', 'Admin\ContactsController');
    Route::post('contacts_mass_destroy', ['uses' => 'Admin\ContactsController@massDestroy', 'as' => 'contacts.mass_destroy']);
    Route::resource('autobuses', 'Admin\AutobusesController');
    Route::post('autobuses_mass_destroy', ['uses' => 'Admin\AutobusesController@massDestroy', 'as' => 'autobuses.mass_destroy']);
    Route::post('autobuses_restore/{id}', ['uses' => 'Admin\AutobusesController@restore', 'as' => 'autobuses.restore']);
    Route::delete('autobuses_perma_del/{id}', ['uses' => 'Admin\AutobusesController@perma_del', 'as' => 'autobuses.perma_del']);
    Route::resource('chofers', 'Admin\ChofersController');
    Route::post('chofers_mass_destroy', ['uses' => 'Admin\ChofersController@massDestroy', 'as' => 'chofers.mass_destroy']);
    Route::post('chofers_restore/{id}', ['uses' => 'Admin\ChofersController@restore', 'as' => 'chofers.restore']);
    Route::delete('chofers_perma_del/{id}', ['uses' => 'Admin\ChofersController@perma_del', 'as' => 'chofers.perma_del']);
    Route::resource('corridas', 'Admin\CorridasController');
    Route::post('corridas_mass_destroy', ['uses' => 'Admin\CorridasController@massDestroy', 'as' => 'corridas.mass_destroy']);
    Route::post('corridas_restore/{id}', ['uses' => 'Admin\CorridasController@restore', 'as' => 'corridas.restore']);
    Route::delete('corridas_perma_del/{id}', ['uses' => 'Admin\CorridasController@perma_del', 'as' => 'corridas.perma_del']);
    Route::resource('configuracions', 'Admin\ConfiguracionsController');
    Route::post('configuracions_mass_destroy', ['uses' => 'Admin\ConfiguracionsController@massDestroy', 'as' => 'configuracions.mass_destroy']);
    Route::post('configuracions_restore/{id}', ['uses' => 'Admin\ConfiguracionsController@restore', 'as' => 'configuracions.restore']);
    Route::delete('configuracions_perma_del/{id}', ['uses' => 'Admin\ConfiguracionsController@perma_del', 'as' => 'configuracions.perma_del']);
    Route::resource('asientos', 'Admin\AsientosController');
    Route::post('asientos_mass_destroy', ['uses' => 'Admin\AsientosController@massDestroy', 'as' => 'asientos.mass_destroy']);
    Route::post('asientos_restore/{id}', ['uses' => 'Admin\AsientosController@restore', 'as' => 'asientos.restore']);
    Route::delete('asientos_perma_del/{id}', ['uses' => 'Admin\AsientosController@perma_del', 'as' => 'asientos.perma_del']);
    Route::get('reservaciones/imprimir/{clave}','Admin\ImpresionControlleler@imprimirBoleto');
    Route::get('/reservaciones/cambios','Admin\ReservacionesController@boletoCambio')->name('reservaciones.cambios');
    Route::resource('reservaciones', 'Admin\ReservacionesController');
    Route::post('reservaciones_mass_destroy', ['uses' => 'Admin\ReservacionesController@massDestroy', 'as' => 'reservaciones.mass_destroy']);
    Route::post('reservaciones_restore/{id}', ['uses' => 'Admin\ReservacionesController@restore', 'as' => 'reservaciones.restore']);
    Route::delete('reservaciones_perma_del/{id}', ['uses' => 'Admin\ReservacionesController@perma_del', 'as' => 'reservaciones.perma_del']);
    Route::resource('reservars', 'Admin\ReservarsController');
    Route::resource('corte_de_cajas', 'Admin\CorteDeCajasController');
    Route::resource('corte_de_cajas_basico', 'Admin\CorteCajaBasicoController');
    Route::resource('liquidaciones', 'Admin\ListaLiquidacionesController');
    Route::post('/spatie/media/upload', 'Admin\SpatieMediaController@create')->name('media.upload');
    Route::post('/spatie/media/remove', 'Admin\SpatieMediaController@destroy')->name('media.remove');

    Route::resource('reporte_corrida','Admin\ReporteCorridaController');
    Route::get('excel/reporte_corrida','Admin\ExcelController@reporteCorrida');
    Route::get('excel/reporte_paqueteria','Admin\ExcelController@reportePaqueteria');

    Route::get('/reservaciones/liquidar/{clave}', 'Admin\ReservacionesController@boletoLiquidacion');
    Route::get('/reservaciones/cancelar/{clave}','Admin\ReservacionesController@boletoCancelacion');
    Route::get('/contabilidad_de_boletos',['uses' => 'Admin\ContabilidadBoletosController@index', 'as' => 'contabiliad.boletos']);

    Route::get('/envios/imprimir/{clave}', 'Admin\ImpresionControlleler@imprimirEnvio');
    Route::get('/envios/pago-entrega/{clave}', 'Admin\EnviosController@envioPagoEntrega');
    Route::get('/envios/pagar/{clave}', 'Admin\EnviosController@envioPagar');
    Route::get('/envios/entrega/{clave}', 'Admin\EnviosController@envioEntrega');
    Route::get('/envios/cancelar/{clave}', 'Admin\EnviosController@envioCancelacion');
    Route::resource('envios', 'Admin\EnviosController');
    //Route::get('buscar_envio', 'Admin\EnviosController@buscarEnvio');
    Route::resource('cliente', 'Admin\ClientController');
    Route::resource('sucursales', 'Admin\SucursalesController');
    Route::post('sucursales_mass_destroy', ['uses' => 'Admin\SucursalesController@massDestroy', 'as' => 'sucursales.mass_destroy']);
    Route::post('sucursales_restore/{id}', ['uses' => 'Admin\SucursalesController@restore', 'as' => 'sucursales.restore']);
    Route::delete('sucursales_perma_del/{id}', ['uses' => 'Admin\SucursalesController@perma_del', 'as' => 'sucursales.perma_del']);

    //Paypalrefund Controler
    Route::get('/paypal/code_search', 'Admin\RefundController@index')->name('code_search');
    //Route::post('/paypal/paypal_set_refund', 'Admin\RefundController@setPaypalRefund');
    Route::get('/paypal/paypal_execute_refund/{clave_global}', 'Admin\RefundController@executePayPalRefund');

});

app/ContactCompany.php
<?php
namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * Class ContactCompany
 *
 * @package App
 * @property string $name
 * @property string $address
 * @property string $website
 * @property string $email
*/
class ContactCompany extends Model
{
    protected $fillable = ['name', 'address', 'website', 'email'];
    protected $hidden = [];
    
    
    public static function boot()
    {
        parent::boot();

        ContactCompany::observe(new \App\Observers\UserActionsObserver);
    }
    
}

app/Http/Controllers/Admin/ContactCompaniesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\ContactCompany;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\StoreContactCompaniesRequest;
use App\Http\Requests\Admin\UpdateContactCompaniesRequest;

class ContactCompaniesController extends Controller
{
    /**
     * Display a listing of ContactCompany.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (! Gate::allows('contact_company_access')) {
            return abort(401);
        }


                $contact_companies = ContactCompany::all();

        return view('admin.contact_companies.index', compact('contact_companies'));
    }

    /**
     * Show the form for creating new ContactCompany.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (! Gate::allows('contact_company_create')) {
            return abort(401);
        }
        return view('admin.contact_companies.create');
    }

    /**
     * Store a newly created ContactCompany in storage.
     *
     * @param  \App\Http\Requests\StoreContactCompaniesRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreContactCompaniesRequest $request)
    {
        if (! Gate::allows('contact_company_create')) {
            return abort(401);
        }
        $contact_company = ContactCompany::create($request->all());



        return redirect()->route('admin.contact_companies.index');
    }


    /**
     * Show the form for editing ContactCompany.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (! Gate::allows('contact_company_edit')) {
            return abort(401);
        }
        $contact_company = ContactCompany::findOrFail($id);

        return view('admin.contact_companies.edit', compact('contact_company'));
    }

    /**
     * Update ContactCompany in storage.
     *
     * @param  \App\Http\Requests\UpdateContactCompaniesRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateContactCompaniesRequest $request, $id)
    {
        if (! Gate::allows('contact_company_edit')) {
            return abort(401);
        }
        $contact_company = ContactCompany::findOrFail($id);
        $contact_company->update($request->all());



        return redirect()->route('admin.contact_companies.index');
    }


    /**
     * Display ContactCompany.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if (! Gate::allows('contact_company_view')) {
            return abort(401);
        }
        $contacts = \App\Contact::where('company_id', $id)->get();

        $contact_company = ContactCompany::findOrFail($id);

        return view('admin.contact_companies.show', compact('contact_company', 'contacts'));
    }


    /**
     * Remove ContactCompany from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (! Gate::allows('contact_company_delete')) {
            return abort(401);
        }
        $contact_company = ContactCompany::findOrFail($id);
        $contact_company->delete();

        return redirect()->route('admin.contact_companies.index');
    }

    /**
     * Delete all selected ContactCompany at once.
     *
     * @param Request $request
     */
    public function massDestroy(Request $request)
    {
        if (! Gate::allows('contact_company_delete')) {
            return abort(401);
        }
        if ($request->input('ids')) {
            $entries = ContactCompany::whereIn('id', $request->input('ids'))->get();

            foreach ($entries as $entry) {
                $entry->delete();
            }
        }
    }

}

resources/views/admin/contact_companies/create.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.contact-companies.title')</h3>
    {!! Form::open(['method' => 'POST', 'route' => ['admin.contact_companies.store']]) !!}

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_create')
        </div>
        
        <div class="panel-body">
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('name', trans('quickadmin.contact-companies.fields.name').'', ['class' => 'control-label']) !!}
                    {!! Form::text('name', old('name'), ['class' => 'form-control', 'placeholder' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('name'))
                        <p class="help-block">
                            {{ $errors->first('name') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('address', trans('quickadmin.contact-companies.fields.address').'', ['class' => 'control-label']) !!}
                    {!! Form::text('address', old('address'), ['class' => 'form-control', 'placeholder' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('address'))
                        <p class="help-block">
                            {{ $errors->first('address') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('website', trans('quickadmin.contact-companies.fields.website').'', ['class' => 'control-label']) !!}
                    {!! Form::text('website', old('website'), ['class' => 'form-control', 'placeholder' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('website'))
                        <p class="help-block">
                            {{ $errors->first('website') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('email', trans('quickadmin.contact-companies.fields.email').'', ['class' => 'control-label']) !!}
                    {!! Form::text('email', old('email'), ['class' => 'form-control', 'placeholder' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('email'))
                        <p class="help-block">
                            {{ $errors->first('email') }}
                        </p>
                    @endif
                </div>
            </div>
            
        </div>
    </div>

    {!! Form::submit(trans('quickadmin.qa_save'), ['class' => 'btn btn-danger']) !!}
    {!! Form::close() !!}
@stop

resources/views/admin/contact_companies/edit.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.contact-companies.title')</h3>
    
    {!! Form::model($contact_company, ['method' => 'PUT', 'route' => ['admin.contact_companies.update', $contact_company->id]]) !!}

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_edit')
        </div>

        <div class="panel-body">
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('name', trans('quickadmin.contact-companies.fields.name').'', ['class' => 'control-label']) !!}
                    {!! Form::text('name', old('name'), ['class' => 'form-control', 'placeholder' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('name'))
                        <p class="help-block">
                            {{ $errors->first('name') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('address', trans('quickadmin.contact-companies.fields.address').'', ['class' => 'control-label']) !!}
                    {!! Form::text('address', old('address'), ['class' => 'form-control', 'placeholder' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('address'))
                        <p class="help-block">
                            {{ $errors->first('address') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('website', trans('quickadmin.contact-companies.fields.website').'', ['class' => 'control-label']) !!}
                    {!! Form::text('website', old('website'), ['class' => 'form-control', 'placeholder' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('website'))
                        <p class="help-block">
                            {{ $errors->first('website') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('email', trans('quickadmin.contact-companies.fields.email').'', ['class' => 'control-label']) !!}
                    {!! Form::text('email', old('email'), ['class' => 'form-control', 'placeholder' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('email'))
                        <p class="help-block">
                            {{ $errors->first('email') }}
                        </p>
                    @endif
                </div>
            </div>
            
        </div>
    </div>

    {!! Form::submit(trans('quickadmin.qa_update'), ['class' => 'btn btn-danger']) !!}
    {!! Form::close() !!}
@stop

resources/views/admin/contact_companies/index.blade.php
@inject('request', 'Illuminate\Http\Request')
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.contact-companies.title')</h3>
    @can('contact_company_create')
    <p>
        <a href="{{ route('admin.contact_companies.create') }}" class="btn btn-success">@lang('quickadmin.qa_add_new')</a>
        
    </p>
    @endcan

    

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_list')
        </div>

        <div class="panel-body table-responsive">
            <table class="table table-bordered table-striped {{ count($contact_companies) > 0 ? 'datatable' : '' }} @can('contact_company_delete') dt-select @endcan">
                <thead>
                    <tr>
                        @can('contact_company_delete')
                            <th style="text-align:center;"><input type="checkbox" id="select-all" /></th>
                        @endcan

                        <th>@lang('quickadmin.contact-companies.fields.name')</th>
                        <th>@lang('quickadmin.contact-companies.fields.address')</th>
                        <th>@lang('quickadmin.contact-companies.fields.website')</th>
                        <th>@lang('quickadmin.contact-companies.fields.email')</th>
                                                <th>&nbsp;</th>

                    </tr>
                </thead>
                
                <tbody>
                    @if (count($contact_companies) > 0)
                        @foreach ($contact_companies as $contact_company)
                            <tr data-entry-id="{{ $contact_company->id }}">
                                @can('contact_company_delete')
                                    <td></td>
                                @endcan

                                <td field-key='name'>{{ $contact_company->name }}</td>
                                <td field-key='address'>{{ $contact_company->address }}</td>
                                <td field-key='website'>{{ $contact_company->website }}</td>
                                <td field-key='email'>{{ $contact_company->email }}</td>
                                                                <td>
                                    @can('contact_company_view')
                                    <a href="{{ route('admin.contact_companies.show',[$contact_company->id]) }}" class="btn btn-xs btn-primary">@lang('quickadmin.qa_view')</a>
                                    @endcan
                                    @can('contact_company_edit')
                                    <a href="{{ route('admin.contact_companies.edit',[$contact_company->id]) }}" class="btn btn-xs btn-info">@lang('quickadmin.qa_edit')</a>
                                    @endcan
                                    @can('contact_company_delete')
{!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("quickadmin.qa_are_you_sure")."');",
                                        'route' => ['admin.contact_companies.destroy', $contact_company->id])) !!}
                                    {!! Form::submit(trans('quickadmin.qa_delete'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                    @endcan
                                </td>

                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td colspan="9">@lang('quickadmin.qa_no_entries_in_table')</td>
                        </tr>
                    @endif
                </tbody>
            </table>
        </div>
    </div>
@stop

@section('javascript') 
    <script>
        @can('contact_company_delete')
            window.route_mass_crud_entries_destroy = '{{ route('admin.contact_companies.mass_destroy') }}';
        @endcan

    </script>
@endsection

resources/views/admin/contact_companies/show.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.contact-companies.title')</h3>

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_view')
        </div>

        <div class="panel-body table-responsive">
            <div class="row">
                <div class="col-md-6">
                    <table class="table table-bordered table-striped">
                        <tr>
                            <th>@lang('quickadmin.contact-companies.fields.name')</th>
                            <td field-key='name'>{{ $contact_company->name }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.contact-companies.fields.address')</th>
                            <td field-key='address'>{{ $contact_company->address }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.contact-companies.fields.website')</th>
                            <td field-key='website'>{{ $contact_company->website }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.contact-companies.fields.email')</th>
                            <td field-key='email'>{{ $contact_company->email }}</td>
                        </tr>
                    </table>
                </div>
            </div><!-- Nav tabs -->
<ul class="nav nav-tabs" role="tablist">
    
<li role="presentation" class="active"><a href="#contacts" aria-controls="contacts" role="tab" data-toggle="tab">Contactos</a></li>
</ul>

<!-- Tab panes -->
<div class="tab-content">
    
<div role="tabpanel" class="tab-pane active" id="contacts">
<table class="table table-bordered table-striped {{ count($contacts) > 0 ? 'datatable' : '' }}">
    <thead>
        <tr>
            <th>@lang('quickadmin.contacts.fields.company')</th>
                        <th>@lang('quickadmin.contacts.fields.first-name')</th>
                        <th>@lang('quickadmin.contacts.fields.last-name')</th>
                        <th>@lang('quickadmin.contacts.fields.phone1')</th>
                        <th>@lang('quickadmin.contacts.fields.phone2')</th>
                        <th>@lang('quickadmin.contacts.fields.email')</th>
                        <th>@lang('quickadmin.contacts.fields.skype')</th>
                        <th>@lang('quickadmin.contacts.fields.address')</th>
                                                <th>&nbsp;</th>

        </tr>
    </thead>

    <tbody>
        @if (count($contacts) > 0)
            @foreach ($contacts as $contact)
                <tr data-entry-id="{{ $contact->id }}">
                    <td field-key='company'>{{ $contact->company->name or '' }}</td>
                                <td field-key='first_name'>{{ $contact->first_name }}</td>
                                <td field-key='last_name'>{{ $contact->last_name }}</td>
                                <td field-key='phone1'>{{ $contact->phone1 }}</td>
                                <td field-key='phone2'>{{ $contact->phone2 }}</td>
                                <td field-key='email'>{{ $contact->email }}</td>
                                <td field-key='skype'>{{ $contact->skype }}</td>
                                <td field-key='address'>{{ $contact->address }}</td>
                                                                <td>
                                    @can('contact_view')
                                    <a href="{{ route('admin.contacts.show',[$contact->id]) }}" class="btn btn-xs btn-primary">@lang('quickadmin.qa_view')</a>
                                    @endcan
                                    @can('contact_edit')
                                    <a href="{{ route('admin.contacts.edit',[$contact->id]) }}" class="btn btn-xs btn-info">@lang('quickadmin.qa_edit')</a>
                                    @endcan
                                    @can('contact_delete')
{!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("quickadmin.qa_are_you_sure")."');",
                                        'route' => ['admin.contacts.destroy', $contact->id])) !!}
                                    {!! Form::submit(trans('quickadmin.qa_delete'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                    @endcan
                                </td>

                </tr>
            @endforeach
        @else
            <tr>
                <td colspan="13">@lang('quickadmin.qa_no_entries_in_table')</td>
            </tr>
        @endif
    </tbody>
</table>
</div>
</div>

            <p>&nbsp;</p>

            <a href="{{ route('admin.contact_companies.index') }}" class="btn btn-default">@lang('quickadmin.qa_back_to_list')</a>
        </div>
    </div>
@stop