routes/web.php
<?php
Route::get('/', function () {
  if(env('PLATAFORMA_RESERVACIONES') == true) {
    return redirect(('/pageWeb'));
  }
  else {
    return redirect('/admin/home');
  }
});
Route::get('/pageWeb', 'Plataforma\FrontendController@index');
Route::any('/reservar/renderBus', 'Plataforma\ReservacionController@renderBus');
Route::resource('/reservar', 'Plataforma\ReservacionController');
/*Route::get('/pagoconpaypal', function(){

    return view('frontend.paypal');
});*/

Route::get('/pagoconpaypal/{clave}', 'Plataforma\PaymentController@create')->name('pagoconpaypal');
Route::post('/paypal', 'Plataforma\PaymentController@payWithpaypal');
Route::get('/status', 'Plataforma\PaymentController@getPaymentStatus')->name('status');


// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('login', 'Auth\LoginController@login')->name('auth.login');
$this->post('logout', 'Auth\LoginController@logout')->name('auth.logout');

// Change Password Routes...
$this->get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
$this->patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');

Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index');

    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'Admin\UsersController');
    Route::post('users_mass_destroy', ['uses' => 'Admin\UsersController@massDestroy', 'as' => 'users.mass_destroy']);
    Route::resource('user_actions', 'Admin\UserActionsController');
    Route::resource('contact_companies', 'Admin\ContactCompaniesController');
    Route::post('contact_companies_mass_destroy', ['uses' => 'Admin\ContactCompaniesController@massDestroy', 'as' => 'contact_companies.mass_destroy']);
    Route::resource('contacts', 'Admin\ContactsController');
    Route::post('contacts_mass_destroy', ['uses' => 'Admin\ContactsController@massDestroy', 'as' => 'contacts.mass_destroy']);
    Route::resource('autobuses', 'Admin\AutobusesController');
    Route::post('autobuses_mass_destroy', ['uses' => 'Admin\AutobusesController@massDestroy', 'as' => 'autobuses.mass_destroy']);
    Route::post('autobuses_restore/{id}', ['uses' => 'Admin\AutobusesController@restore', 'as' => 'autobuses.restore']);
    Route::delete('autobuses_perma_del/{id}', ['uses' => 'Admin\AutobusesController@perma_del', 'as' => 'autobuses.perma_del']);
    Route::resource('chofers', 'Admin\ChofersController');
    Route::post('chofers_mass_destroy', ['uses' => 'Admin\ChofersController@massDestroy', 'as' => 'chofers.mass_destroy']);
    Route::post('chofers_restore/{id}', ['uses' => 'Admin\ChofersController@restore', 'as' => 'chofers.restore']);
    Route::delete('chofers_perma_del/{id}', ['uses' => 'Admin\ChofersController@perma_del', 'as' => 'chofers.perma_del']);
    Route::resource('corridas', 'Admin\CorridasController');
    Route::post('corridas_mass_destroy', ['uses' => 'Admin\CorridasController@massDestroy', 'as' => 'corridas.mass_destroy']);
    Route::post('corridas_restore/{id}', ['uses' => 'Admin\CorridasController@restore', 'as' => 'corridas.restore']);
    Route::delete('corridas_perma_del/{id}', ['uses' => 'Admin\CorridasController@perma_del', 'as' => 'corridas.perma_del']);
    Route::resource('configuracions', 'Admin\ConfiguracionsController');
    Route::post('configuracions_mass_destroy', ['uses' => 'Admin\ConfiguracionsController@massDestroy', 'as' => 'configuracions.mass_destroy']);
    Route::post('configuracions_restore/{id}', ['uses' => 'Admin\ConfiguracionsController@restore', 'as' => 'configuracions.restore']);
    Route::delete('configuracions_perma_del/{id}', ['uses' => 'Admin\ConfiguracionsController@perma_del', 'as' => 'configuracions.perma_del']);
    Route::resource('asientos', 'Admin\AsientosController');
    Route::post('asientos_mass_destroy', ['uses' => 'Admin\AsientosController@massDestroy', 'as' => 'asientos.mass_destroy']);
    Route::post('asientos_restore/{id}', ['uses' => 'Admin\AsientosController@restore', 'as' => 'asientos.restore']);
    Route::delete('asientos_perma_del/{id}', ['uses' => 'Admin\AsientosController@perma_del', 'as' => 'asientos.perma_del']);
    Route::get('reservaciones/imprimir/{clave}','Admin\ImpresionControlleler@imprimirBoleto');
    Route::get('/reservaciones/cambios','Admin\ReservacionesController@boletoCambio')->name('reservaciones.cambios');
    Route::resource('reservaciones', 'Admin\ReservacionesController');
    Route::post('reservaciones_mass_destroy', ['uses' => 'Admin\ReservacionesController@massDestroy', 'as' => 'reservaciones.mass_destroy']);
    Route::post('reservaciones_restore/{id}', ['uses' => 'Admin\ReservacionesController@restore', 'as' => 'reservaciones.restore']);
    Route::delete('reservaciones_perma_del/{id}', ['uses' => 'Admin\ReservacionesController@perma_del', 'as' => 'reservaciones.perma_del']);
    Route::resource('reservars', 'Admin\ReservarsController');
    Route::resource('corte_de_cajas', 'Admin\CorteDeCajasController');
    Route::resource('corte_de_cajas_basico', 'Admin\CorteCajaBasicoController');
    Route::resource('liquidaciones', 'Admin\ListaLiquidacionesController');
    Route::post('/spatie/media/upload', 'Admin\SpatieMediaController@create')->name('media.upload');
    Route::post('/spatie/media/remove', 'Admin\SpatieMediaController@destroy')->name('media.remove');

    Route::resource('reporte_corrida','Admin\ReporteCorridaController');
    Route::get('excel/reporte_corrida','Admin\ExcelController@reporteCorrida');
    Route::get('excel/reporte_paqueteria','Admin\ExcelController@reportePaqueteria');

    Route::get('/reservaciones/liquidar/{clave}', 'Admin\ReservacionesController@boletoLiquidacion');
    Route::get('/reservaciones/cancelar/{clave}','Admin\ReservacionesController@boletoCancelacion');
    Route::get('/contabilidad_de_boletos',['uses' => 'Admin\ContabilidadBoletosController@index', 'as' => 'contabiliad.boletos']);

    Route::get('/envios/imprimir/{clave}', 'Admin\ImpresionControlleler@imprimirEnvio');
    Route::get('/envios/pago-entrega/{clave}', 'Admin\EnviosController@envioPagoEntrega');
    Route::get('/envios/pagar/{clave}', 'Admin\EnviosController@envioPagar');
    Route::get('/envios/entrega/{clave}', 'Admin\EnviosController@envioEntrega');
    Route::get('/envios/cancelar/{clave}', 'Admin\EnviosController@envioCancelacion');
    Route::resource('envios', 'Admin\EnviosController');
    //Route::get('buscar_envio', 'Admin\EnviosController@buscarEnvio');
    Route::resource('cliente', 'Admin\ClientController');
    Route::resource('sucursales', 'Admin\SucursalesController');
    Route::post('sucursales_mass_destroy', ['uses' => 'Admin\SucursalesController@massDestroy', 'as' => 'sucursales.mass_destroy']);
    Route::post('sucursales_restore/{id}', ['uses' => 'Admin\SucursalesController@restore', 'as' => 'sucursales.restore']);
    Route::delete('sucursales_perma_del/{id}', ['uses' => 'Admin\SucursalesController@perma_del', 'as' => 'sucursales.perma_del']);

    //Paypalrefund Controler
    Route::get('/paypal/code_search', 'Admin\RefundController@index')->name('code_search');
    //Route::post('/paypal/paypal_set_refund', 'Admin\RefundController@setPaypalRefund');
    Route::get('/paypal/paypal_execute_refund/{clave_global}', 'Admin\RefundController@executePayPalRefund');

});

app/Chofer.php
<?php
namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\HasMedia\Interfaces\HasMedia;

/**
 * Class Chofer
 *
 * @package App
 * @property string $nombre
 * @property string $edad
 * @property string $domicilio
 * @property string $domicili_gmaps
 * @property string $telefono
 * @property string $celular
 * @property text $nota
 * @property string $correo
*/
class Chofer extends Model implements HasMedia
{
    use SoftDeletes, HasMediaTrait;

    protected $fillable = ['nombre', 'edad', 'domicilio', 'telefono', 'celular', 'nota', 'correo', 'domicili_gmaps_address', 'domicili_gmaps_latitude', 'domicili_gmaps_longitude'];
    protected $hidden = [];
    
    
    public static function boot()
    {
        parent::boot();

        Chofer::observe(new \App\Observers\UserActionsObserver);
    }
    
}

app/Http/Controllers/Admin/ChofersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Chofer;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\StoreChofersRequest;
use App\Http\Requests\Admin\UpdateChofersRequest;
use App\Http\Controllers\Traits\FileUploadTrait;

class ChofersController extends Controller
{
    use FileUploadTrait;

    /**
     * Display a listing of Chofer.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (! Gate::allows('chofer_access')) {
            return abort(401);
        }


        if (request('show_deleted') == 1) {
            if (! Gate::allows('chofer_delete')) {
                return abort(401);
            }
            $chofers = Chofer::onlyTrashed()->get();
        } else {
            $chofers = Chofer::all();
        }

        return view('admin.chofers.index', compact('chofers'));
    }

    /**
     * Show the form for creating new Chofer.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (! Gate::allows('chofer_create')) {
            return abort(401);
        }
        return view('admin.chofers.create');
    }

    /**
     * Store a newly created Chofer in storage.
     *
     * @param  \App\Http\Requests\StoreChofersRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreChofersRequest $request)
    {
        if (! Gate::allows('chofer_create')) {
            return abort(401);
        }
        $request = $this->saveFiles($request);
        $chofer = Chofer::create($request->all());


        foreach ($request->input('documentos_id', []) as $index => $id) {
            $model          = config('laravel-medialibrary.media_model');
            $file           = $model::find($id);
            $file->model_id = $chofer->id;
            $file->save();
        }

        return redirect()->route('admin.chofers.index');
    }


    /**
     * Show the form for editing Chofer.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (! Gate::allows('chofer_edit')) {
            return abort(401);
        }
        $chofer = Chofer::findOrFail($id);

        return view('admin.chofers.edit', compact('chofer'));
    }

    /**
     * Update Chofer in storage.
     *
     * @param  \App\Http\Requests\UpdateChofersRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateChofersRequest $request, $id)
    {
        if (! Gate::allows('chofer_edit')) {
            return abort(401);
        }
        $request = $this->saveFiles($request);
        $chofer = Chofer::findOrFail($id);
        $chofer->update($request->all());


        $media = [];
        foreach ($request->input('documentos_id', []) as $index => $id) {
            $model          = config('laravel-medialibrary.media_model');
            $file           = $model::find($id);
            $file->model_id = $chofer->id;
            $file->save();
            $media[] = $file->toArray();
        }
        $chofer->updateMedia($media, 'documentos');

        return redirect()->route('admin.chofers.index');
    }


    /**
     * Display Chofer.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if (! Gate::allows('chofer_view')) {
            return abort(401);
        }
        $corridas = \App\Corrida::where('chofer_id', $id)->get();

        $chofer = Chofer::findOrFail($id);

        return view('admin.chofers.show', compact('chofer', 'corridas'));
    }


    /**
     * Remove Chofer from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (! Gate::allows('chofer_delete')) {
            return abort(401);
        }
        $chofer = Chofer::findOrFail($id);
        $chofer->deletePreservingMedia();

        return redirect()->route('admin.chofers.index');
    }

    /**
     * Delete all selected Chofer at once.
     *
     * @param Request $request
     */
    public function massDestroy(Request $request)
    {
        if (! Gate::allows('chofer_delete')) {
            return abort(401);
        }
        if ($request->input('ids')) {
            $entries = Chofer::whereIn('id', $request->input('ids'))->get();

            foreach ($entries as $entry) {
                $entry->deletePreservingMedia();
            }
        }
    }


    /**
     * Restore Chofer from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function restore($id)
    {
        if (! Gate::allows('chofer_delete')) {
            return abort(401);
        }
        $chofer = Chofer::onlyTrashed()->findOrFail($id);
        $chofer->restore();

        return redirect()->route('admin.chofers.index');
    }

    /**
     * Permanently delete Chofer from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function perma_del($id)
    {
        if (! Gate::allows('chofer_delete')) {
            return abort(401);
        }
        $chofer = Chofer::onlyTrashed()->findOrFail($id);
        $chofer->forceDelete();

        return redirect()->route('admin.chofers.index');
    }
}

resources/views/admin/chofers/show.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.chofer.title')</h3>

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_view')
        </div>

        <div class="panel-body table-responsive">
            <div class="row">
                <div class="col-md-6">
                    <table class="table table-bordered table-striped">
                        <tr>
                            <th>@lang('quickadmin.chofer.fields.nombre')</th>
                            <td field-key='nombre'>{{ $chofer->nombre }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.chofer.fields.edad')</th>
                            <td field-key='edad'>{{ $chofer->edad }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.chofer.fields.domicilio')</th>
                            <td field-key='domicilio'>{{ $chofer->domicilio }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.chofer.fields.domicili-gmaps')</th>
                            <td field-key='domicili_gmaps'>{{ $chofer->domicili_gmaps_address }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.chofer.fields.telefono')</th>
                            <td field-key='telefono'>{{ $chofer->telefono }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.chofer.fields.documentos')</th>
                            <td field-key='documentos's> @foreach($chofer->getMedia('documentos') as $media)
                                <p class="form-group">
                                    <a href="{{ $media->getUrl() }}" target="_blank">{{ $media->name }} ({{ $media->size }} KB)</a>
                                </p>
                            @endforeach</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.chofer.fields.nota')</th>
                            <td field-key='nota'>{!! $chofer->nota !!}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.chofer.fields.correo')</th>
                            <td field-key='correo'>{{ $chofer->correo }}</td>
                        </tr>
                    </table>
                </div>
            </div><!-- Nav tabs -->
<ul class="nav nav-tabs" role="tablist">
    
<li role="presentation" class="active"><a href="#corridas" aria-controls="corridas" role="tab" data-toggle="tab">Corridas</a></li>
</ul>

<!-- Tab panes -->
<div class="tab-content">
    
<div role="tabpanel" class="tab-pane active" id="corridas">
<table class="table table-bordered table-striped {{ count($corridas) > 0 ? 'datatable' : '' }}">
    <thead>
        <tr>
            <th>@lang('quickadmin.corridas.fields.nombre')</th>
                        <th>@lang('quickadmin.corridas.fields.hora-salida')</th>
                        <th>@lang('quickadmin.corridas.fields.costo-boleto-sencillo')</th>
                        <th>@lang('quickadmin.corridas.fields.costo-boleto-redondo')</th>
                        <th>@lang('quickadmin.corridas.fields.total-asientos')</th>
                        <th>@lang('quickadmin.corridas.fields.observaciones')</th>
                        <th>@lang('quickadmin.corridas.fields.generar-lunes')</th>
                        <th>@lang('quickadmin.corridas.fields.generar-martes')</th>
                        <th>@lang('quickadmin.corridas.fields.generar-miercoles')</th>
                        <th>@lang('quickadmin.corridas.fields.generar-jueves')</th>
                        <th>@lang('quickadmin.corridas.fields.generar-viernes')</th>
                        <th>@lang('quickadmin.corridas.fields.generar-sabado')</th>
                        <th>@lang('quickadmin.corridas.fields.generar-domingo')</th>
                        <th>@lang('quickadmin.corridas.fields.chofer')</th>
                        <th>@lang('quickadmin.corridas.fields.autobus')</th>
                        @if( request('show_deleted') == 1 )
                        <th>&nbsp;</th>
                        @else
                        <th>&nbsp;</th>
                        @endif
        </tr>
    </thead>

    <tbody>
        @if (count($corridas) > 0)
            @foreach ($corridas as $corrida)
                <tr data-entry-id="{{ $corrida->id }}">
                    <td field-key='nombre'>{{ $corrida->nombre }}</td>
                                <td field-key='hora_salida'>{{ $corrida->hora_salida }}</td>
                                <td field-key='costo_boleto_sencillo'>{{ $corrida->costo_boleto_sencillo }}</td>
                                <td field-key='costo_boleto_redondo'>{{ $corrida->costo_boleto_redondo }}</td>
                                <td field-key='total_asientos'>{{ $corrida->total_asientos }}</td>
                                <td field-key='observaciones'>{!! $corrida->observaciones !!}</td>
                                <td field-key='generar_lunes'>{{ Form::checkbox("generar_lunes", 1, $corrida->generar_lunes == 1 ? true : false, ["disabled"]) }}</td>
                                <td field-key='generar_martes'>{{ Form::checkbox("generar_martes", 1, $corrida->generar_martes == 1 ? true : false, ["disabled"]) }}</td>
                                <td field-key='generar_miercoles'>{{ Form::checkbox("generar_miercoles", 1, $corrida->generar_miercoles == 1 ? true : false, ["disabled"]) }}</td>
                                <td field-key='generar_jueves'>{{ Form::checkbox("generar_jueves", 1, $corrida->generar_jueves == 1 ? true : false, ["disabled"]) }}</td>
                                <td field-key='generar_viernes'>{{ Form::checkbox("generar_viernes", 1, $corrida->generar_viernes == 1 ? true : false, ["disabled"]) }}</td>
                                <td field-key='generar_sabado'>{{ Form::checkbox("generar_sabado", 1, $corrida->generar_sabado == 1 ? true : false, ["disabled"]) }}</td>
                                <td field-key='generar_domingo'>{{ Form::checkbox("generar_domingo", 1, $corrida->generar_domingo == 1 ? true : false, ["disabled"]) }}</td>
                                <td field-key='chofer'>{{ $corrida->chofer->nombre or '' }}</td>
                                <td field-key='autobus'>{{ $corrida->autobus->placas or '' }}</td>
                                @if( request('show_deleted') == 1 )
                                <td>
                                    @can('corrida_delete')
                                                                        {!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'POST',
                                        'onsubmit' => "return confirm('".trans("quickadmin.qa_are_you_sure")."');",
                                        'route' => ['admin.corridas.restore', $corrida->id])) !!}
                                    {!! Form::submit(trans('quickadmin.qa_restore'), array('class' => 'btn btn-xs btn-success')) !!}
                                    {!! Form::close() !!}
                                @endcan
                                    @can('corrida_delete')
                                                                        {!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("quickadmin.qa_are_you_sure")."');",
                                        'route' => ['admin.corridas.perma_del', $corrida->id])) !!}
                                    {!! Form::submit(trans('quickadmin.qa_permadel'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                @endcan
                                </td>
                                @else
                                <td>
                                    @can('corrida_view')
                                    <a href="{{ route('admin.corridas.show',[$corrida->id]) }}" class="btn btn-xs btn-primary">@lang('quickadmin.qa_view')</a>
                                    @endcan
                                    @can('corrida_edit')
                                    <a href="{{ route('admin.corridas.edit',[$corrida->id]) }}" class="btn btn-xs btn-info">@lang('quickadmin.qa_edit')</a>
                                    @endcan
                                    @can('corrida_delete')
{!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("quickadmin.qa_are_you_sure")."');",
                                        'route' => ['admin.corridas.destroy', $corrida->id])) !!}
                                    {!! Form::submit(trans('quickadmin.qa_delete'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                    @endcan
                                </td>
                                @endif
                </tr>
            @endforeach
        @else
            <tr>
                <td colspan="20">@lang('quickadmin.qa_no_entries_in_table')</td>
            </tr>
        @endif
    </tbody>
</table>
</div>
</div>

            <p>&nbsp;</p>

            <a href="{{ route('admin.chofers.index') }}" class="btn btn-default">@lang('quickadmin.qa_back_to_list')</a>
        </div>
    </div>
@stop