routes/web.php
<?php
Route::get('/', function () {
  if(env('PLATAFORMA_RESERVACIONES') == true) {
    return redirect(('/pageWeb'));
  }
  else {
    return redirect('/admin/home');
  }
});
Route::get('/pageWeb', 'Plataforma\FrontendController@index');
Route::any('/reservar/renderBus', 'Plataforma\ReservacionController@renderBus');
Route::resource('/reservar', 'Plataforma\ReservacionController');
/*Route::get('/pagoconpaypal', function(){

    return view('frontend.paypal');
});*/

Route::get('/pagoconpaypal/{clave}', 'Plataforma\PaymentController@create')->name('pagoconpaypal');
Route::post('/paypal', 'Plataforma\PaymentController@payWithpaypal');
Route::get('/status', 'Plataforma\PaymentController@getPaymentStatus')->name('status');


// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('login', 'Auth\LoginController@login')->name('auth.login');
$this->post('logout', 'Auth\LoginController@logout')->name('auth.logout');

// Change Password Routes...
$this->get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
$this->patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');

Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index');

    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'Admin\UsersController');
    Route::post('users_mass_destroy', ['uses' => 'Admin\UsersController@massDestroy', 'as' => 'users.mass_destroy']);
    Route::resource('user_actions', 'Admin\UserActionsController');
    Route::resource('contact_companies', 'Admin\ContactCompaniesController');
    Route::post('contact_companies_mass_destroy', ['uses' => 'Admin\ContactCompaniesController@massDestroy', 'as' => 'contact_companies.mass_destroy']);
    Route::resource('contacts', 'Admin\ContactsController');
    Route::post('contacts_mass_destroy', ['uses' => 'Admin\ContactsController@massDestroy', 'as' => 'contacts.mass_destroy']);
    Route::resource('autobuses', 'Admin\AutobusesController');
    Route::post('autobuses_mass_destroy', ['uses' => 'Admin\AutobusesController@massDestroy', 'as' => 'autobuses.mass_destroy']);
    Route::post('autobuses_restore/{id}', ['uses' => 'Admin\AutobusesController@restore', 'as' => 'autobuses.restore']);
    Route::delete('autobuses_perma_del/{id}', ['uses' => 'Admin\AutobusesController@perma_del', 'as' => 'autobuses.perma_del']);
    Route::resource('chofers', 'Admin\ChofersController');
    Route::post('chofers_mass_destroy', ['uses' => 'Admin\ChofersController@massDestroy', 'as' => 'chofers.mass_destroy']);
    Route::post('chofers_restore/{id}', ['uses' => 'Admin\ChofersController@restore', 'as' => 'chofers.restore']);
    Route::delete('chofers_perma_del/{id}', ['uses' => 'Admin\ChofersController@perma_del', 'as' => 'chofers.perma_del']);
    Route::resource('corridas', 'Admin\CorridasController');
    Route::post('corridas_mass_destroy', ['uses' => 'Admin\CorridasController@massDestroy', 'as' => 'corridas.mass_destroy']);
    Route::post('corridas_restore/{id}', ['uses' => 'Admin\CorridasController@restore', 'as' => 'corridas.restore']);
    Route::delete('corridas_perma_del/{id}', ['uses' => 'Admin\CorridasController@perma_del', 'as' => 'corridas.perma_del']);
    Route::resource('configuracions', 'Admin\ConfiguracionsController');
    Route::post('configuracions_mass_destroy', ['uses' => 'Admin\ConfiguracionsController@massDestroy', 'as' => 'configuracions.mass_destroy']);
    Route::post('configuracions_restore/{id}', ['uses' => 'Admin\ConfiguracionsController@restore', 'as' => 'configuracions.restore']);
    Route::delete('configuracions_perma_del/{id}', ['uses' => 'Admin\ConfiguracionsController@perma_del', 'as' => 'configuracions.perma_del']);
    Route::resource('asientos', 'Admin\AsientosController');
    Route::post('asientos_mass_destroy', ['uses' => 'Admin\AsientosController@massDestroy', 'as' => 'asientos.mass_destroy']);
    Route::post('asientos_restore/{id}', ['uses' => 'Admin\AsientosController@restore', 'as' => 'asientos.restore']);
    Route::delete('asientos_perma_del/{id}', ['uses' => 'Admin\AsientosController@perma_del', 'as' => 'asientos.perma_del']);
    Route::get('reservaciones/imprimir/{clave}','Admin\ImpresionControlleler@imprimirBoleto');
    Route::get('/reservaciones/cambios','Admin\ReservacionesController@boletoCambio')->name('reservaciones.cambios');
    Route::resource('reservaciones', 'Admin\ReservacionesController');
    Route::post('reservaciones_mass_destroy', ['uses' => 'Admin\ReservacionesController@massDestroy', 'as' => 'reservaciones.mass_destroy']);
    Route::post('reservaciones_restore/{id}', ['uses' => 'Admin\ReservacionesController@restore', 'as' => 'reservaciones.restore']);
    Route::delete('reservaciones_perma_del/{id}', ['uses' => 'Admin\ReservacionesController@perma_del', 'as' => 'reservaciones.perma_del']);
    Route::resource('reservars', 'Admin\ReservarsController');
    Route::resource('corte_de_cajas', 'Admin\CorteDeCajasController');
    Route::resource('corte_de_cajas_basico', 'Admin\CorteCajaBasicoController');
    Route::resource('liquidaciones', 'Admin\ListaLiquidacionesController');
    Route::post('/spatie/media/upload', 'Admin\SpatieMediaController@create')->name('media.upload');
    Route::post('/spatie/media/remove', 'Admin\SpatieMediaController@destroy')->name('media.remove');

    Route::resource('reporte_corrida','Admin\ReporteCorridaController');
    Route::get('excel/reporte_corrida','Admin\ExcelController@reporteCorrida');
    Route::get('excel/reporte_paqueteria','Admin\ExcelController@reportePaqueteria');

    Route::get('/reservaciones/liquidar/{clave}', 'Admin\ReservacionesController@boletoLiquidacion');
    Route::get('/reservaciones/cancelar/{clave}','Admin\ReservacionesController@boletoCancelacion');
    Route::get('/contabilidad_de_boletos',['uses' => 'Admin\ContabilidadBoletosController@index', 'as' => 'contabiliad.boletos']);

    Route::get('/envios/imprimir/{clave}', 'Admin\ImpresionControlleler@imprimirEnvio');
    Route::get('/envios/pago-entrega/{clave}', 'Admin\EnviosController@envioPagoEntrega');
    Route::get('/envios/pagar/{clave}', 'Admin\EnviosController@envioPagar');
    Route::get('/envios/entrega/{clave}', 'Admin\EnviosController@envioEntrega');
    Route::get('/envios/cancelar/{clave}', 'Admin\EnviosController@envioCancelacion');
    Route::resource('envios', 'Admin\EnviosController');
    //Route::get('buscar_envio', 'Admin\EnviosController@buscarEnvio');
    Route::resource('cliente', 'Admin\ClientController');
    Route::resource('sucursales', 'Admin\SucursalesController');
    Route::post('sucursales_mass_destroy', ['uses' => 'Admin\SucursalesController@massDestroy', 'as' => 'sucursales.mass_destroy']);
    Route::post('sucursales_restore/{id}', ['uses' => 'Admin\SucursalesController@restore', 'as' => 'sucursales.restore']);
    Route::delete('sucursales_perma_del/{id}', ['uses' => 'Admin\SucursalesController@perma_del', 'as' => 'sucursales.perma_del']);

    //Paypalrefund Controler
    Route::get('/paypal/code_search', 'Admin\RefundController@index')->name('code_search');
    //Route::post('/paypal/paypal_set_refund', 'Admin\RefundController@setPaypalRefund');
    Route::get('/paypal/paypal_execute_refund/{clave_global}', 'Admin\RefundController@executePayPalRefund');

});

app/Http/Controllers/Admin/AutobusesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Autobus;
use App\Asiento;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\StoreAutobusesRequest;
use App\Http\Requests\Admin\UpdateAutobusesRequest;

class AutobusesController extends Controller
{
    /**
     * Display a listing of Autobus.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (! Gate::allows('autobus_access')) {
            return abort(401);
        }


        if (request('show_deleted') == 1) {
            if (! Gate::allows('autobus_delete')) {
                return abort(401);
            }
            $autobuses = Autobus::onlyTrashed()->get();
        } else {
            $autobuses = Autobus::all();
        }

        return view('admin.autobuses.index', compact('autobuses'));
    }

    /**
     * Show the form for creating new Autobus.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (! Gate::allows('autobus_create')) {
            return abort(401);
        }
        return view('admin.autobuses.create');
    }

    /**
     * Store a newly created Autobus in storage.
     *
     * @param  \App\Http\Requests\StoreAutobusesRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreAutobusesRequest $request)
    {
        if (! Gate::allows('autobus_create')) {
            return abort(401);
        }
        $autobus = Autobus::create($request->all());

        return redirect()->route('admin.autobuses.index');
    }


    /**
     * Show the form for editing Autobus.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (! Gate::allows('autobus_edit')) {
            return abort(401);
        }
        $autobus = Autobus::findOrFail($id);

        return view('admin.autobuses.edit', compact('autobus'));
    }

    /**
     * Update Autobus in storage.
     *
     * @param  \App\Http\Requests\UpdateAutobusesRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateAutobusesRequest $request, $id)
    {
        if (! Gate::allows('autobus_edit')) {
            return abort(401);
        }
        $autobus = Autobus::findOrFail($id);
        $autobus->update($request->all());



        return redirect()->route('admin.autobuses.index');
    }


    /**
     * Display Autobus.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if (! Gate::allows('autobus_view')) {
            return abort(401);
        }
        //$asientos = \App\Asiento::where('autobus_id', $id)->get();$corridas = \App\Corrida::where('autobus_id', $id)->get();

        $autobus = Autobus::findOrFail($id);

        return view('admin.autobuses.show', compact('autobus', 'corridas'));
    }


    /**
     * Remove Autobus from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (! Gate::allows('autobus_delete')) {
            return abort(401);
        }
        $autobus = Autobus::findOrFail($id);
        $autobus->delete();

        return redirect()->route('admin.autobuses.index');
    }

    /**
     * Delete all selected Autobus at once.
     *
     * @param Request $request
     */
    public function massDestroy(Request $request)
    {
        if (! Gate::allows('autobus_delete')) {
            return abort(401);
        }
        if ($request->input('ids')) {
            $entries = Autobus::whereIn('id', $request->input('ids'))->get();

            foreach ($entries as $entry) {
                $entry->delete();
            }
        }
    }


    /**
     * Restore Autobus from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function restore($id)
    {
        if (! Gate::allows('autobus_delete')) {
            return abort(401);
        }
        $autobus = Autobus::onlyTrashed()->findOrFail($id);
        $autobus->restore();

        return redirect()->route('admin.autobuses.index');
    }

    /**
     * Permanently delete Autobus from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function perma_del($id)
    {
        if (! Gate::allows('autobus_delete')) {
            return abort(401);
        }
        $autobus = Autobus::onlyTrashed()->findOrFail($id);
        $autobus->forceDelete();

        return redirect()->route('admin.autobuses.index');
    }
}

resources/views/admin/autobuses/create.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.autobus.title')</h3>
    {!! Form::open(['method' => 'POST', 'route' => ['admin.autobuses.store']]) !!}

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_create')
        </div>

        <div class="panel-body">

            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('marca', trans('quickadmin.autobus.fields.marca').'*', ['class' => 'control-label']) !!}
                    {!! Form::text('marca', old('marca'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('marca'))
                        <p class="help-block">
                            {{ $errors->first('marca') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('modelo', trans('quickadmin.autobus.fields.modelo').'*', ['class' => 'control-label']) !!}
                    {!! Form::text('modelo', old('modelo'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('modelo'))
                        <p class="help-block">
                            {{ $errors->first('modelo') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('placas', trans('quickadmin.autobus.fields.placas').'*', ['class' => 'control-label']) !!}
                    {!! Form::text('placas', old('placas'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('placas'))
                        <p class="help-block">
                            {{ $errors->first('placas') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('propietario', trans('quickadmin.autobus.fields.propietario').'*', ['class' => 'control-label']) !!}
                    {!! Form::text('propietario', old('propietario'), ['class' => 'form-control', 'placeholder' => 'Escribe el nombre del propietario', 'required' => '']) !!}
                    <p class="help-block">Escribe el nombre del propietario</p>
                    @if($errors->has('propietario'))
                        <p class="help-block">
                            {{ $errors->first('propietario') }}
                        </p>
                    @endif
                </div>
            </div>

            <div class="row">
                <div class="col-xs-12 form-group">
                  <label for="asientos">{{trans('quickadmin.autobus.fields.numero-asientos').''}}</label>
                  <select class="form-control" id="asientos" name="numero_asientos">
                    <option value="">-- Selecciona</option>
                    <option value="53" {{old('numero_asientos') == 53? 'selected':''}}>53</option>
                    <option value="51" {{old('numero_asientos') == 51? 'selected':''}}>51</option>
                    <option value="50" {{old('numero_asientos') == 50? 'selected':''}}>50</option>
                    <option value="48" {{old('numero_asientos') == 48? 'selected':''}}>48</option>
                    <option value="47" {{old('numero_asientos') == 47? 'selected':''}}>47</option>
                    <option value="46" {{old('numero_asientos') == 46? 'selected':''}}>46</option>
                    <option value="20" {{old('numero_asientos') == 20? 'selected':''}}>20</option>
                  </select>

                    <p class="help-block"></p>
                    @if($errors->has('numero_asientos'))
                        <p class="help-block">
                            {{ $errors->first('numero_asientos') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('costo_renta', trans('quickadmin.autobus.fields.costo_renta').'*', ['class' => 'control-label']) !!}
                    {!! Form::text('costo_renta', old('costo_renta'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('costo_renta'))
                        <p class="help-block">
                            {{ $errors->first('costo_renta') }}
                        </p>
                    @endif
                </div>
            </div>
            <!--
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('costo_renta', trans('quickadmin.autobus.fields.costo_boleto_sencillo').'*', ['class' => 'control-label']) !!}
                    {!! Form::text('costo_boleto_sencillo', old('costo_boleto_sencillo'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('costo_boleto_sencillo'))
                        <p class="help-block">
                            {{ $errors->first('costo_boleto_sencillo') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('costo_renta', trans('quickadmin.autobus.fields.costo_boleto_redondo').'*', ['class' => 'control-label']) !!}
                    {!! Form::text('costo_boleto_redondo', old('costo_boleto_redondo'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('costo_boleto_redondo'))
                        <p class="help-block">
                            {{ $errors->first('costo_boleto_redondo') }}
                        </p>
                    @endif
                </div>
            </div>
          -->
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('descripcion', trans('quickadmin.autobus.fields.descripcion').'', ['class' => 'control-label']) !!}
                    {!! Form::textarea('descripcion', old('descripcion'), ['class' => 'form-control ', 'placeholder' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('descripcion'))
                        <p class="help-block">
                            {{ $errors->first('descripcion') }}
                        </p>
                    @endif
                </div>
            </div>

        </div>
    </div>

    {!! Form::submit(trans('quickadmin.qa_save'), ['class' => 'btn btn-danger']) !!}
    {!! Form::close() !!}
@stop

resources/views/admin/autobuses/index.blade.php
@inject('request', 'Illuminate\Http\Request')
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.autobus.title')</h3>
    @can('autobus_create')
    <p>
        <a href="{{ route('admin.autobuses.create') }}" class="btn btn-success">@lang('quickadmin.qa_add_new')</a>
        
    </p>
    @endcan

    @can('autobus_delete')
    <p>
        <ul class="list-inline">
            <li><a href="{{ route('admin.autobuses.index') }}" style="{{ request('show_deleted') == 1 ? '' : 'font-weight: 700' }}">@lang('quickadmin.qa_all')</a></li> |
            <li><a href="{{ route('admin.autobuses.index') }}?show_deleted=1" style="{{ request('show_deleted') == 1 ? 'font-weight: 700' : '' }}">@lang('quickadmin.qa_trash')</a></li>
        </ul>
    </p>
    @endcan


    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_list')
        </div>

        <div class="panel-body table-responsive">
            <table class="table table-bordered table-striped {{ count($autobuses) > 0 ? 'datatable' : '' }} @can('autobus_delete') @if ( request('show_deleted') != 1 ) dt-select @endif @endcan">
                <thead>
                    <tr>
                        @can('autobus_delete')
                            @if ( request('show_deleted') != 1 )<th style="text-align:center;"><input type="checkbox" id="select-all" /></th>@endif
                        @endcan

                        <th>@lang('quickadmin.autobus.fields.marca')</th>
                        <th>@lang('quickadmin.autobus.fields.modelo')</th>
                        <th>@lang('quickadmin.autobus.fields.placas')</th>
                        <th>@lang('quickadmin.autobus.fields.propietario')</th>
                        <th>@lang('quickadmin.autobus.fields.numero-asientos')</th>
                        <th>@lang('quickadmin.autobus.fields.descripcion')</th>
                        @if( request('show_deleted') == 1 )
                        <th>&nbsp;</th>
                        @else
                        <th>&nbsp;</th>
                        @endif
                    </tr>
                </thead>
                
                <tbody>
                    @if (count($autobuses) > 0)
                        @foreach ($autobuses as $autobus)
                            <tr data-entry-id="{{ $autobus->id }}">
                                @can('autobus_delete')
                                    @if ( request('show_deleted') != 1 )<td></td>@endif
                                @endcan

                                <td field-key='marca'>{{ $autobus->marca }}</td>
                                <td field-key='modelo'>{{ $autobus->modelo }}</td>
                                <td field-key='placas'>{{ $autobus->placas }}</td>
                                <td field-key='propietario'>{{ $autobus->propietario }}</td>
                                <td field-key='numero_asientos'>{{ $autobus->numero_asientos }}</td>
                                <td field-key='descripcion'>{!! $autobus->descripcion !!}</td>
                                @if( request('show_deleted') == 1 )
                                <td>
                                    @can('autobus_delete')
                                                                        {!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'POST',
                                        'onsubmit' => "return confirm('".trans("quickadmin.qa_are_you_sure")."');",
                                        'route' => ['admin.autobuses.restore', $autobus->id])) !!}
                                    {!! Form::submit(trans('quickadmin.qa_restore'), array('class' => 'btn btn-xs btn-success')) !!}
                                    {!! Form::close() !!}
                                @endcan
                                    @can('autobus_delete')
                                                                        {!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("quickadmin.qa_are_you_sure")."');",
                                        'route' => ['admin.autobuses.perma_del', $autobus->id])) !!}
                                    {!! Form::submit(trans('quickadmin.qa_permadel'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                @endcan
                                </td>
                                @else
                                <td>
                                    @can('autobus_view')
                                    <a href="{{ route('admin.autobuses.show',[$autobus->id]) }}" class="btn btn-xs btn-primary">@lang('quickadmin.qa_view')</a>
                                    @endcan
                                    @can('autobus_edit')
                                    <a href="{{ route('admin.autobuses.edit',[$autobus->id]) }}" class="btn btn-xs btn-info">@lang('quickadmin.qa_edit')</a>
                                    @endcan
                                    @can('autobus_delete')
{!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("quickadmin.qa_are_you_sure")."');",
                                        'route' => ['admin.autobuses.destroy', $autobus->id])) !!}
                                    {!! Form::submit(trans('quickadmin.qa_delete'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                    @endcan
                                </td>
                                @endif
                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td colspan="11">@lang('quickadmin.qa_no_entries_in_table')</td>
                        </tr>
                    @endif
                </tbody>
            </table>
        </div>
    </div>
@stop

@section('javascript') 
    <script>
        @can('autobus_delete')
            @if ( request('show_deleted') != 1 ) window.route_mass_crud_entries_destroy = '{{ route('admin.autobuses.mass_destroy') }}'; @endif
        @endcan

    </script>
@endsection

resources/views/admin/autobuses/show.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.autobus.title')</h3>

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_view')
        </div>

        <div class="panel-body table-responsive">
            <div class="row">
                <div class="col-md-6">
                    <table class="table table-bordered table-striped">
                        <tr>
                            <th>@lang('quickadmin.autobus.fields.marca')</th>
                            <td field-key='marca'>{{ $autobus->marca }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.autobus.fields.modelo')</th>
                            <td field-key='modelo'>{{ $autobus->modelo }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.autobus.fields.placas')</th>
                            <td field-key='placas'>{{ $autobus->placas }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.autobus.fields.propietario')</th>
                            <td field-key='propietario'>{{ $autobus->propietario }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.autobus.fields.numero-asientos')</th>
                            <td field-key='numero_asientos'>{{ $autobus->numero_asientos }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.autobus.fields.descripcion')</th>
                            <td field-key='descripcion'>{!! $autobus->descripcion !!}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.autobus.fields.costo_renta')</th>
                            <td field-key='costo_renta'>{!! number_format($autobus->costo_renta,2) !!}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.autobus.fields.costo_boleto_redondo')</th>
                            <td field-key='costo_boleto_redondo'>{!! number_format($autobus->costo_boleto_redondo,2) !!}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.autobus.fields.costo_boleto_sencillo')</th>
                            <td field-key='costo_boleto_sencillo'>{!! number_format($autobus->costo_boleto_sencillo,2) !!}</td>
                        </tr>
                    </table>
                </div>
            </div><!-- Nav tabs -->

            <p>&nbsp;</p>

            <a href="{{ route('admin.autobuses.index') }}" class="btn btn-default">@lang('quickadmin.qa_back_to_list')</a>
        </div>
    </div>
@stop