routes/web.php
<?php
Route::get('/', function () {
  if(env('PLATAFORMA_RESERVACIONES') == true) {
    return redirect(('/pageWeb'));
  }
  else {
    return redirect('/admin/home');
  }
});
Route::get('/pageWeb', 'Plataforma\FrontendController@index');
Route::any('/reservar/renderBus', 'Plataforma\ReservacionController@renderBus');
Route::resource('/reservar', 'Plataforma\ReservacionController');
/*Route::get('/pagoconpaypal', function(){

    return view('frontend.paypal');
});*/

Route::get('/pagoconpaypal/{clave}', 'Plataforma\PaymentController@create')->name('pagoconpaypal');
Route::post('/paypal', 'Plataforma\PaymentController@payWithpaypal');
Route::get('/status', 'Plataforma\PaymentController@getPaymentStatus')->name('status');


// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('login', 'Auth\LoginController@login')->name('auth.login');
$this->post('logout', 'Auth\LoginController@logout')->name('auth.logout');

// Change Password Routes...
$this->get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
$this->patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');

Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index');

    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'Admin\UsersController');
    Route::post('users_mass_destroy', ['uses' => 'Admin\UsersController@massDestroy', 'as' => 'users.mass_destroy']);
    Route::resource('user_actions', 'Admin\UserActionsController');
    Route::resource('contact_companies', 'Admin\ContactCompaniesController');
    Route::post('contact_companies_mass_destroy', ['uses' => 'Admin\ContactCompaniesController@massDestroy', 'as' => 'contact_companies.mass_destroy']);
    Route::resource('contacts', 'Admin\ContactsController');
    Route::post('contacts_mass_destroy', ['uses' => 'Admin\ContactsController@massDestroy', 'as' => 'contacts.mass_destroy']);
    Route::resource('autobuses', 'Admin\AutobusesController');
    Route::post('autobuses_mass_destroy', ['uses' => 'Admin\AutobusesController@massDestroy', 'as' => 'autobuses.mass_destroy']);
    Route::post('autobuses_restore/{id}', ['uses' => 'Admin\AutobusesController@restore', 'as' => 'autobuses.restore']);
    Route::delete('autobuses_perma_del/{id}', ['uses' => 'Admin\AutobusesController@perma_del', 'as' => 'autobuses.perma_del']);
    Route::resource('chofers', 'Admin\ChofersController');
    Route::post('chofers_mass_destroy', ['uses' => 'Admin\ChofersController@massDestroy', 'as' => 'chofers.mass_destroy']);
    Route::post('chofers_restore/{id}', ['uses' => 'Admin\ChofersController@restore', 'as' => 'chofers.restore']);
    Route::delete('chofers_perma_del/{id}', ['uses' => 'Admin\ChofersController@perma_del', 'as' => 'chofers.perma_del']);
    Route::resource('corridas', 'Admin\CorridasController');
    Route::post('corridas_mass_destroy', ['uses' => 'Admin\CorridasController@massDestroy', 'as' => 'corridas.mass_destroy']);
    Route::post('corridas_restore/{id}', ['uses' => 'Admin\CorridasController@restore', 'as' => 'corridas.restore']);
    Route::delete('corridas_perma_del/{id}', ['uses' => 'Admin\CorridasController@perma_del', 'as' => 'corridas.perma_del']);
    Route::resource('configuracions', 'Admin\ConfiguracionsController');
    Route::post('configuracions_mass_destroy', ['uses' => 'Admin\ConfiguracionsController@massDestroy', 'as' => 'configuracions.mass_destroy']);
    Route::post('configuracions_restore/{id}', ['uses' => 'Admin\ConfiguracionsController@restore', 'as' => 'configuracions.restore']);
    Route::delete('configuracions_perma_del/{id}', ['uses' => 'Admin\ConfiguracionsController@perma_del', 'as' => 'configuracions.perma_del']);
    Route::resource('asientos', 'Admin\AsientosController');
    Route::post('asientos_mass_destroy', ['uses' => 'Admin\AsientosController@massDestroy', 'as' => 'asientos.mass_destroy']);
    Route::post('asientos_restore/{id}', ['uses' => 'Admin\AsientosController@restore', 'as' => 'asientos.restore']);
    Route::delete('asientos_perma_del/{id}', ['uses' => 'Admin\AsientosController@perma_del', 'as' => 'asientos.perma_del']);
    Route::get('reservaciones/imprimir/{clave}','Admin\ImpresionControlleler@imprimirBoleto');
    Route::get('/reservaciones/cambios','Admin\ReservacionesController@boletoCambio')->name('reservaciones.cambios');
    Route::resource('reservaciones', 'Admin\ReservacionesController');
    Route::post('reservaciones_mass_destroy', ['uses' => 'Admin\ReservacionesController@massDestroy', 'as' => 'reservaciones.mass_destroy']);
    Route::post('reservaciones_restore/{id}', ['uses' => 'Admin\ReservacionesController@restore', 'as' => 'reservaciones.restore']);
    Route::delete('reservaciones_perma_del/{id}', ['uses' => 'Admin\ReservacionesController@perma_del', 'as' => 'reservaciones.perma_del']);
    Route::resource('reservars', 'Admin\ReservarsController');
    Route::resource('corte_de_cajas', 'Admin\CorteDeCajasController');
    Route::resource('corte_de_cajas_basico', 'Admin\CorteCajaBasicoController');
    Route::resource('liquidaciones', 'Admin\ListaLiquidacionesController');
    Route::post('/spatie/media/upload', 'Admin\SpatieMediaController@create')->name('media.upload');
    Route::post('/spatie/media/remove', 'Admin\SpatieMediaController@destroy')->name('media.remove');

    Route::resource('reporte_corrida','Admin\ReporteCorridaController');
    Route::get('excel/reporte_corrida','Admin\ExcelController@reporteCorrida');
    Route::get('excel/reporte_paqueteria','Admin\ExcelController@reportePaqueteria');

    Route::get('/reservaciones/liquidar/{clave}', 'Admin\ReservacionesController@boletoLiquidacion');
    Route::get('/reservaciones/cancelar/{clave}','Admin\ReservacionesController@boletoCancelacion');
    Route::get('/contabilidad_de_boletos',['uses' => 'Admin\ContabilidadBoletosController@index', 'as' => 'contabiliad.boletos']);

    Route::get('/envios/imprimir/{clave}', 'Admin\ImpresionControlleler@imprimirEnvio');
    Route::get('/envios/pago-entrega/{clave}', 'Admin\EnviosController@envioPagoEntrega');
    Route::get('/envios/pagar/{clave}', 'Admin\EnviosController@envioPagar');
    Route::get('/envios/entrega/{clave}', 'Admin\EnviosController@envioEntrega');
    Route::get('/envios/cancelar/{clave}', 'Admin\EnviosController@envioCancelacion');
    Route::resource('envios', 'Admin\EnviosController');
    //Route::get('buscar_envio', 'Admin\EnviosController@buscarEnvio');
    Route::resource('cliente', 'Admin\ClientController');
    Route::resource('sucursales', 'Admin\SucursalesController');
    Route::post('sucursales_mass_destroy', ['uses' => 'Admin\SucursalesController@massDestroy', 'as' => 'sucursales.mass_destroy']);
    Route::post('sucursales_restore/{id}', ['uses' => 'Admin\SucursalesController@restore', 'as' => 'sucursales.restore']);
    Route::delete('sucursales_perma_del/{id}', ['uses' => 'Admin\SucursalesController@perma_del', 'as' => 'sucursales.perma_del']);

    //Paypalrefund Controler
    Route::get('/paypal/code_search', 'Admin\RefundController@index')->name('code_search');
    //Route::post('/paypal/paypal_set_refund', 'Admin\RefundController@setPaypalRefund');
    Route::get('/paypal/paypal_execute_refund/{clave_global}', 'Admin\RefundController@executePayPalRefund');

});

app/Asiento.php
<?php
namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class Asiento
 *
 * @package App
 * @property integer $numero
 * @property string $corrida
*/
class Asiento extends Model
{
    use SoftDeletes;

    protected $fillable = ['numero', 'corrida_id'];
    protected $hidden = [];


    public static function boot()
    {
        parent::boot();

        Asiento::observe(new \App\Observers\UserActionsObserver);
    }

    /**
     * Set attribute to money format
     * @param $input
     */
    public function setNumeroAttribute($input)
    {
        $this->attributes['numero'] = $input ? $input : null;
    }

    /**
     * Set to null if empty
     * @param $input
     */
    public function setAutobusIdAttribute($input)
    {
        $this->attributes['corrida_id'] = $input ? $input : null;
    }

    public function corrida()
    {
        return $this->belongsTo(Corrida::class, 'corrida_id')->withTrashed();
    }

    public function reservacion(){
      return $this->hasOne(Reservacione::class,'asiento_id')->withTrashed();
    }

}

app/Http/Controllers/Admin/AsientosController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Asiento;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\StoreAsientosRequest;
use App\Http\Requests\Admin\UpdateAsientosRequest;

class AsientosController extends Controller
{
    /**
     * Display a listing of Asiento.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (! Gate::allows('asiento_access')) {
            return abort(401);
        }


        if (request('show_deleted') == 1) {
            if (! Gate::allows('asiento_delete')) {
                return abort(401);
            }
            $asientos = Asiento::onlyTrashed()->get();
        } else {
            $asientos = Asiento::all();
        }

        return view('admin.asientos.index', compact('asientos'));
    }

    /**
     * Show the form for creating new Asiento.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (! Gate::allows('asiento_create')) {
            return abort(401);
        }

        $corridas = \App\Corrida::get()->pluck('nombre', 'id')->prepend(trans('quickadmin.qa_please_select'), '');

        return view('admin.asientos.create', compact('corridas'));
    }

    /**
     * Store a newly created Asiento in storage.
     *
     * @param  \App\Http\Requests\StoreAsientosRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreAsientosRequest $request)
    {
        if (! Gate::allows('asiento_create')) {
            return abort(401);
        }
        $asiento = Asiento::create($request->all());



        return redirect()->route('admin.asientos.index');
    }


    /**
     * Show the form for editing Asiento.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (! Gate::allows('asiento_edit')) {
            return abort(401);
        }

        $corridas = \App\Corrida::get()->pluck('nombre', 'id')->prepend(trans('quickadmin.qa_please_select'), '');

        $asiento = Asiento::findOrFail($id);

        return view('admin.asientos.edit', compact('asiento', 'corridas'));
    }

    /**
     * Update Asiento in storage.
     *
     * @param  \App\Http\Requests\UpdateAsientosRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateAsientosRequest $request, $id)
    {
        if (! Gate::allows('asiento_edit')) {
            return abort(401);
        }
        $asiento = Asiento::findOrFail($id);
        $asiento->update($request->all());



        return redirect()->route('admin.asientos.index');
    }


    /**
     * Display Asiento.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if (! Gate::allows('asiento_view')) {
            return abort(401);
        }

        $autobuses = \App\Autobus::get()->pluck('placas', 'id')->prepend(trans('quickadmin.qa_please_select'), '');$reservaciones = \App\Reservacione::where('asiento_id', $id)->get();

        $asiento = Asiento::findOrFail($id);

        return view('admin.asientos.show', compact('asiento', 'reservaciones'));
    }


    /**
     * Remove Asiento from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (! Gate::allows('asiento_delete')) {
            return abort(401);
        }
        $asiento = Asiento::findOrFail($id);
        $asiento->delete();

        return redirect()->route('admin.asientos.index');
    }

    /**
     * Delete all selected Asiento at once.
     *
     * @param Request $request
     */
    public function massDestroy(Request $request)
    {
        if (! Gate::allows('asiento_delete')) {
            return abort(401);
        }
        if ($request->input('ids')) {
            $entries = Asiento::whereIn('id', $request->input('ids'))->get();

            foreach ($entries as $entry) {
                $entry->delete();
            }
        }
    }


    /**
     * Restore Asiento from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function restore($id)
    {
        if (! Gate::allows('asiento_delete')) {
            return abort(401);
        }
        $asiento = Asiento::onlyTrashed()->findOrFail($id);
        $asiento->restore();

        return redirect()->route('admin.asientos.index');
    }

    /**
     * Permanently delete Asiento from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function perma_del($id)
    {
        if (! Gate::allows('asiento_delete')) {
            return abort(401);
        }
        $asiento = Asiento::onlyTrashed()->findOrFail($id);
        $asiento->forceDelete();

        return redirect()->route('admin.asientos.index');
    }
}

resources/views/admin/asientos/create.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.asiento.title')</h3>
    {!! Form::open(['method' => 'POST', 'route' => ['admin.asientos.store']]) !!}

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_create')
        </div>

        <div class="panel-body">
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('numero', trans('quickadmin.asiento.fields.numero').'*', ['class' => 'control-label']) !!}
                    {!! Form::number('numero', old('numero'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('numero'))
                        <p class="help-block">
                            {{ $errors->first('numero') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('corrida_id', trans('quickadmin.asiento.fields.corrida').'*', ['class' => 'control-label']) !!}
                    {!! Form::select('corrida_id', $corridas, old('corrida_id'), ['class' => 'form-control select2', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('corrida_id'))
                        <p class="help-block">
                            {{ $errors->first('corrida_id') }}
                        </p>
                    @endif
                </div>
            </div>

        </div>
    </div>

    {!! Form::submit(trans('quickadmin.qa_save'), ['class' => 'btn btn-danger']) !!}
    {!! Form::close() !!}
@stop

resources/views/admin/asientos/edit.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.asiento.title')</h3>

    {!! Form::model($asiento, ['method' => 'PUT', 'route' => ['admin.asientos.update', $asiento->id]]) !!}

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_edit')
        </div>

        <div class="panel-body">
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('numero', trans('quickadmin.asiento.fields.numero').'*', ['class' => 'control-label']) !!}
                    {!! Form::number('numero', old('numero'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('numero'))
                        <p class="help-block">
                            {{ $errors->first('numero') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('corrida_id', trans('quickadmin.asiento.fields.corrida').'*', ['class' => 'control-label']) !!}
                    {!! Form::select('corrida_id', $corridas, old('corrida_id'), ['class' => 'form-control select2', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('corrida_id'))
                        <p class="help-block">
                            {{ $errors->first('corrida_id') }}
                        </p>
                    @endif
                </div>
            </div>

        </div>
    </div>

    {!! Form::submit(trans('quickadmin.qa_update'), ['class' => 'btn btn-danger']) !!}
    {!! Form::close() !!}
@stop

resources/views/admin/asientos/index.blade.php
@inject('request', 'Illuminate\Http\Request')
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.asiento.title')</h3>
    @can('asiento_create')
    <p>
        <a href="{{ route('admin.asientos.create') }}" class="btn btn-success">@lang('quickadmin.qa_add_new')</a>

    </p>
    @endcan

    @can('asiento_delete')
    <p>
        <ul class="list-inline">
            <li><a href="{{ route('admin.asientos.index') }}" style="{{ request('show_deleted') == 1 ? '' : 'font-weight: 700' }}">@lang('quickadmin.qa_all')</a></li> |
            <li><a href="{{ route('admin.asientos.index') }}?show_deleted=1" style="{{ request('show_deleted') == 1 ? 'font-weight: 700' : '' }}">@lang('quickadmin.qa_trash')</a></li>
        </ul>
    </p>
    @endcan


    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_list')
        </div>

        <div class="panel-body table-responsive">
            <table class="table table-bordered table-striped {{ count($asientos) > 0 ? 'datatable' : '' }} @can('asiento_delete') @if ( request('show_deleted') != 1 ) dt-select @endif @endcan">
                <thead>
                    <tr>
                        @can('asiento_delete')
                            @if ( request('show_deleted') != 1 )<th style="text-align:center;"><input type="checkbox" id="select-all" /></th>@endif
                        @endcan

                        <th>@lang('quickadmin.asiento.fields.numero')</th>
                        <th>@lang('quickadmin.asiento.fields.corrida')</th>
                        @if( request('show_deleted') == 1 )
                        <th>&nbsp;</th>
                        @else
                        <th>&nbsp;</th>
                        @endif
                    </tr>
                </thead>

                <tbody>
                    @if (count($asientos) > 0)
                        @foreach ($asientos as $asiento)
                            <tr data-entry-id="{{ $asiento->id }}">
                                @can('asiento_delete')
                                    @if ( request('show_deleted') != 1 )<td></td>@endif
                                @endcan

                                <td field-key='numero'>{{ $asiento->numero }}</td>
                                <td field-key='autobus'>{{ $asiento->corrida->nombre }} {{ $asiento->corrida->hora_salida}}</td>
                                @if( request('show_deleted') == 1 )
                                <td>
                                    @can('asiento_delete')
                                                                        {!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'POST',
                                        'onsubmit' => "return confirm('".trans("quickadmin.qa_are_you_sure")."');",
                                        'route' => ['admin.asientos.restore', $asiento->id])) !!}
                                    {!! Form::submit(trans('quickadmin.qa_restore'), array('class' => 'btn btn-xs btn-success')) !!}
                                    {!! Form::close() !!}
                                @endcan
                                    @can('asiento_delete')
                                                                        {!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("quickadmin.qa_are_you_sure")."');",
                                        'route' => ['admin.asientos.perma_del', $asiento->id])) !!}
                                    {!! Form::submit(trans('quickadmin.qa_permadel'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                @endcan
                                </td>
                                @else
                                <td>
                                    @can('asiento_view')
                                    <a href="{{ route('admin.asientos.show',[$asiento->id]) }}" class="btn btn-xs btn-primary">@lang('quickadmin.qa_view')</a>
                                    @endcan
                                    @can('asiento_edit')
                                    <a href="{{ route('admin.asientos.edit',[$asiento->id]) }}" class="btn btn-xs btn-info">@lang('quickadmin.qa_edit')</a>
                                    @endcan
                                    @can('asiento_delete')
{!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("quickadmin.qa_are_you_sure")."');",
                                        'route' => ['admin.asientos.destroy', $asiento->id])) !!}
                                    {!! Form::submit(trans('quickadmin.qa_delete'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                    @endcan
                                </td>
                                @endif
                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td colspan="7">@lang('quickadmin.qa_no_entries_in_table')</td>
                        </tr>
                    @endif
                </tbody>
            </table>
        </div>
    </div>
@stop

@section('javascript')
    <script>
        @can('asiento_delete')
            @if ( request('show_deleted') != 1 ) window.route_mass_crud_entries_destroy = '{{ route('admin.asientos.mass_destroy') }}'; @endif
        @endcan

    </script>
@endsection

resources/views/admin/asientos/show.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.asiento.title')</h3>

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_view')
        </div>

        <div class="panel-body table-responsive">
            <div class="row">
                <div class="col-md-6">
                    <table class="table table-bordered table-striped">
                        <tr>
                            <th>@lang('quickadmin.asiento.fields.numero')</th>
                            <td field-key='numero'>{{ $asiento->numero }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.asiento.fields.corrida')</th>
                            <td field-key='autobus'>{{ $asiento->corrida->nombre }} {{ $asiento->corrida->hora_salida }}</td>
                        </tr>
                    </table>
                </div>
            </div><!-- Nav tabs -->
<ul class="nav nav-tabs" role="tablist">

<li role="presentation" class="active"><a href="#reservaciones" aria-controls="reservaciones" role="tab" data-toggle="tab">Reservaciones</a></li>
</ul>

<!-- Tab panes -->
<div class="tab-content">

<div role="tabpanel" class="tab-pane active" id="reservaciones">
<table class="table table-bordered table-striped {{ count($reservaciones) > 0 ? 'datatable' : '' }}">
    <thead>
        <tr>
            <th>@lang('quickadmin.reservaciones.fields.cliente')</th>
                        <th>@lang('quickadmin.reservaciones.fields.costo-boleto')</th>
                        <th>@lang('quickadmin.reservaciones.fields.vendedor')</th>
                        <th>@lang('quickadmin.reservaciones.fields.asiento')</th>
                        <th>@lang('quickadmin.reservaciones.fields.corrida')</th>
                        <th>@lang('quickadmin.reservaciones.fields.clave')</th>
                        <th>@lang('quickadmin.reservaciones.fields.descuento')</th>
                        <th>@lang('quickadmin.reservaciones.fields.observaciones')</th>
                        <th>@lang('quickadmin.reservaciones.fields.comprobante-pago')</th>
                        <th>@lang('quickadmin.reservaciones.fields.estatus')</th>
                        @if( request('show_deleted') == 1 )
                        <th>&nbsp;</th>
                        @else
                        <th>&nbsp;</th>
                        @endif
        </tr>
    </thead>

    <tbody>
        @if (count($reservaciones) > 0)
            @foreach ($reservaciones as $reservacione)
                <tr data-entry-id="{{ $reservacione->id }}">
                    <td field-key='cliente'>{{ $reservacione->cliente }}</td>
                                <td field-key='costo_boleto'>{{ $reservacione->costo_boleto }}</td>
                                <td field-key='vendedor'>{{ $reservacione->vendedor->name or '' }}</td>
                                <td field-key='asiento'>{{ $reservacione->asiento->numero or '' }}</td>
                                <td field-key='corrida'>{{ $reservacione->corrida->nombre or '' }}</td>
                                <td field-key='clave'>{{ $reservacione->clave }}</td>
                                <td field-key='descuento'>{{ Form::checkbox("descuento", 1, $reservacione->descuento == 1 ? true : false, ["disabled"]) }}</td>
                                <td field-key='observaciones'>{!! $reservacione->observaciones !!}</td>
                                <td field-key='comprobante_pago'>@if($reservacione->comprobante_pago)<a href="{{ asset(env('UPLOAD_PATH').'/' . $reservacione->comprobante_pago) }}" target="_blank">Download file</a>@endif</td>
                                <td field-key='estatus'>{{ $reservacione->estatus }}</td>
                                @if( request('show_deleted') == 1 )
                                <td>
                                    @can('reservacione_delete')
                                                                        {!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'POST',
                                        'onsubmit' => "return confirm('".trans("quickadmin.qa_are_you_sure")."');",
                                        'route' => ['admin.reservaciones.restore', $reservacione->id])) !!}
                                    {!! Form::submit(trans('quickadmin.qa_restore'), array('class' => 'btn btn-xs btn-success')) !!}
                                    {!! Form::close() !!}
                                @endcan
                                    @can('reservacione_delete')
                                                                        {!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("quickadmin.qa_are_you_sure")."');",
                                        'route' => ['admin.reservaciones.perma_del', $reservacione->id])) !!}
                                    {!! Form::submit(trans('quickadmin.qa_permadel'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                @endcan
                                </td>
                                @else
                                <td>
                                    @can('reservacione_view')
                                    <a href="{{ route('admin.reservaciones.show',[$reservacione->id]) }}" class="btn btn-xs btn-primary">@lang('quickadmin.qa_view')</a>
                                    @endcan
                                    @can('reservacione_edit')
                                    <a href="{{ route('admin.reservaciones.edit',[$reservacione->id]) }}" class="btn btn-xs btn-info">@lang('quickadmin.qa_edit')</a>
                                    @endcan
                                    @can('reservacione_delete')
{!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("quickadmin.qa_are_you_sure")."');",
                                        'route' => ['admin.reservaciones.destroy', $reservacione->id])) !!}
                                    {!! Form::submit(trans('quickadmin.qa_delete'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                    @endcan
                                </td>
                                @endif
                </tr>
            @endforeach
        @else
            <tr>
                <td colspan="15">@lang('quickadmin.qa_no_entries_in_table')</td>
            </tr>
        @endif
    </tbody>
</table>
</div>
</div>

            <p>&nbsp;</p>

            <a href="{{ route('admin.asientos.index') }}" class="btn btn-default">@lang('quickadmin.qa_back_to_list')</a>
        </div>
    </div>
@stop